kind: "BuildConfig"
apiVersion: "v1"
metadata:
  name: customer-service
spec:
  source:
    git:
      ref: master
      uri: 'https://github.com/mukitul/customer-service.git'
    sourceSecret:
      name: github-secret
    type: Git
  strategy:
    jenkinsPipelineStrategy:
      jenkinsfilePath: jenkins/Jenkinsfile
    type: JenkinsPipeline 

