apiVersion: apps.openshift.io/v1
kind: DeploymentConfig
metadata:
  labels:
    app: treeengine
  name: treeengine
  namespace: remitclick
spec:
  replicas: 1
  selector:
    app: treeengine
    deploymentconfig: treeengine
  strategy:
    activeDeadlineSeconds: 21600
    resources: {}
    type: Recreate
  template:
    metadata:
      labels:
        app: treeengine
        deploymentconfig: treeengine
    spec:
      containers:
        - env:
            - name: MYSQL_DATABASE
              value: TreeEngine
            - name: MYSQL_USER
              value: root
            - name: MYSQL_ALLOW_EMPTY_PASSWORD
              value: 'yes'
          image: 'mysql:5.6'
          imagePullPolicy: IfNotPresent
          name: mysqlserver
          ports:
            - containerPort: 3306
              protocol: TCP
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          volumeMounts:
            - mountPath: /var/lib/mysql
              name: mysql-data

        - image: docker-registry.default.svc:5000/remitclick/tg
          imagePullPolicy: Always
          name: treeengine-service
          ports:
            - containerPort: 8080
              protocol: TCP
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
        - name: mysql-data
          persistentVolumeClaim:
            claimName: rms-te
  triggers:
    - type: ConfigChange

    - imageChangeParams:
        automatic: true
        containerNames:
          - treeengine-service
        from:
          kind: ImageStreamTag
          name: tg:latest
          namespace: remitclick
      type: ImageChange

