apiVersion: v1
kind: Service
metadata:
  labels:
    app: customer-service
  name: customer-service
  namespace: demo
spec:
  ports:
    - name: 8080-tcp
      port: 8080
      protocol: TCP
      targetPort: 8080
  selector:
    deploymentconfig: customer-service
  type: ClusterIP 
